/**
 * Alphachem seed script — uses real data exported from alphachem-db
 * Run: npx tsx scripts/seed.ts
 */

import { config } from 'dotenv'
config({ path: '.env.local' })
import { createClient } from '@supabase/supabase-js'
import slugify from 'slugify'
import { readFileSync, existsSync } from 'fs'
import { join } from 'path'

const SUPABASE_URL = 'https://zgecpsubfiyzgpnlxtny.supabase.co'
const SUPABASE_SERVICE_KEY = process.env.SUPABASE_SERVICE_ROLE_KEY ||
  'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InpnZWNwc3ViZml5emdwbmx4dG55Iiwicm9sZSI6InNlcnZpY2Vfcm9sZSIsImlhdCI6MTc4MDQ2NzAxMCwiZXhwIjoyMDk2MDQzMDEwfQ.FKJIzSrLvWw7iSjCP-moxtk65I1H1Mx2ivWVgtvJrO8'

const supabase = createClient(SUPABASE_URL, SUPABASE_SERVICE_KEY)

const UPLOADS_DIR = join(process.cwd(), 'scripts/uploads/alphachem-uploads')

// ─── Categories (derived from product data) ──────────────────────────────
const CATEGORIES = [
  { slug: 'api',                label_az: 'API (Aktiv)',                  label_en: 'API (Active)',             label_ru: 'API (Активный)',                             sort_order: 1 },
  { slug: 'excipient-pharma',   label_az: 'Excipient (Farma)',            label_en: 'Excipient (Pharma)',       label_ru: 'Вспомогательное вещество (Фарма)',           sort_order: 2 },
  { slug: 'vitamin',            label_az: 'Vitamin',                      label_en: 'Vitamin',                  label_ru: 'Витамин',                                    sort_order: 3 },
  { slug: 'excipient-food',     label_az: 'Excipient (Qida)',             label_en: 'Excipient (Food)',         label_ru: 'Вспомогательное вещество (Пищевое)',         sort_order: 4 },
  { slug: 'excipient-technical',label_az: 'Excipient (Texniki)',          label_en: 'Excipient (Technical)',    label_ru: 'Вспомогательное вещество (Техническое)',     sort_order: 5 },
  { slug: 'intermediate',       label_az: 'Intermediate',                 label_en: 'Intermediate',             label_ru: 'Промежуточный продукт',                      sort_order: 6 },
  { slug: 'other',              label_az: 'Digər kimyəvi maddələr',       label_en: 'Other Chemicals',          label_ru: 'Прочие химикаты',                            sort_order: 7 },
  { slug: 'mineral',            label_az: 'Mineral',                      label_en: 'Mineral',                  label_ru: 'Минерал',                                    sort_order: 8 },
]

// Map old category strings → new slugs
function mapCategory(old: string): string {
  const map: Record<string, string> = {
    'API (ACTIVE)': 'api',
    'EXCIPIENT (PHARMA)': 'excipient-pharma',
    'VITAMIN': 'vitamin',
    'EXCIPIENT (FOOD)': 'excipient-food',
    'EXICIPIENT (TECHNICAL)': 'excipient-technical',
    'EXCIPIENT (TECHNICAL)': 'excipient-technical',
    'INTERMEDIATE': 'intermediate',
    'OTHER CHEMICALS': 'other',
    'MINERAL': 'mineral',
  }
  return map[old.trim()] ?? 'other'
}

// ─── Real products from DB ────────────────────────────────────────────────
const PRODUCTS = [
  { id: 6,  titleAZ: 'Kalsium Xlorid Məhlulu',            titleEN: 'Calcium Chloride Solution',              titleRU: 'Раствор Xлорида Kальция',                   descAZ: 'Formula: CaCl2 IUPAC adı: Kalsium Diklorid Kalsium xlorid məhlulları orta və yüksək konsentrasiyalı maye kalsium xlorid məhlullarıdır. Çözünmüş material tələb edən tətbiqlər üçün əla bir kalsium xlorid qaynağıdır. Metalların və nadir torpaqların həlləri ümumiyyətlə neft -kimya krekinq və avtomobil katalizatorları, su təmizləmə, elektrokaplama, tekstil, tədqiqat, eləcə də optika, lazer, kristal və şüşədə istifadə olunur.',                                                                                  descEN: 'Formula: CaCl2 IUPAC Name: calcium dichloride. Calcium Chloride Solutions are moderate to highly concentrated liquid solutions of Calcium Chloride. They are an excellent source of Calcium Chloride for applications requiring solubilized materials. Commonly used in petrochemical cracking and automotive catalysts, water treatment, plating, textiles, research and in optic, laser, crystal and glass applications.',  descRU: 'Формула: CaCl2 Название IUPAC: дихлорид кальция. Растворы хлорида кальция представляют собой жидкие растворы хлорида кальция с умеренной и высокой концентрацией. Они являются отличным источником хлорида кальция для применений, требующих солюбилизированных материалов.',  category: 'EXICIPIENT (TECHNICAL)', imageFile: 'upload-533ae6abd429bda38c46c42d098bfd105.jpg' },
  { id: 1,  titleAZ: 'Antifriz 1kg',                      titleEN: 'Antifreeze 1kg',                         titleRU: 'Антифриз 1kg',                              descAZ: 'Antifriz — mənfi temperatur şəraitində daxiliyanma mühərriklərini soyutmaq üçün işlədilən çətindonan mayedir. Əsas antifriz mayeləri kimi etilen qlikol, propilen qlikol, qliserin və digər maddələrin su ilə qarışıqları istifadə olunur.',                                                                                                                                                                                                                                                                                                                                                                              descEN: 'Antifreeze is a generic name for fluids that do not freeze at low temperatures. They are used for cooling internal combustion engines, as aviation de-icing fluids and as a glass cleaner. Mixtures of ethylene glycol, propylene glycol, glycerin and other substances with water are used as base fluids for antifreeze.',                                                                                                  descRU: 'Антифриз — общее название для жидкостей, не замерзающих при низких температурах. Применяются для охлаждения двигателей внутреннего сгорания, в качестве авиационных противообледенительных жидкостей и в качестве средства для очистки стекол.',                                                                             category: 'OTHER CHEMICALS',        imageFile: 'upload-54723e5b310dfac92ef6d4b5a0e56fe46.png' },
  { id: 2,  titleAZ: 'Antifriz 5kg',                      titleEN: 'Antifreeze 5kg',                         titleRU: 'Антифриз 5kg',                              descAZ: 'Antifriz — mənfi temperatur şəraitində daxiliyanma mühərriklərini soyutmaq üçün işlədilən çətindonan mayedir. Əsas antifriz mayeləri kimi etilen qlikol, propilen qlikol, qliserin və digər maddələrin su ilə qarışıqları istifadə olunur.',                                                                                                                                                                                                                                                                                                                                                                              descEN: 'Antifreeze is a generic name for fluids that do not freeze at low temperatures. 5kg package.',                                                                                                                                                                                                                                                                                                                               descRU: 'Антифриз — общее название для жидкостей, не замерзающих при низких температурах. Упаковка 5 кг.',                                                                                                                                                                                                                            category: 'OTHER CHEMICALS',        imageFile: 'upload-e58f7d6610a2d10a77f79615893241d037.png' },
  { id: 9,  titleAZ: 'Kalsium Hidroksid',                 titleEN: 'Calcium Hydroxide',                      titleRU: 'Гидроксид Кальция',                         descAZ: 'Formula: Ca(OH)2 IUPAC nömrəsi: Kalsium hidroksid. Molar kütlə: 74.093 g/mol Sıxlıq: 2.21 g/sm³ Ərimə nöqtəsi: 580°C. Kalsium hidroksid, sönməmiş əhəngə su əlavə etməklə əmələ gələn kimyəvi birləşmədir. Kristal ağ toz şəklində mövcuddur. Suda həll edildikdə pasta bir görünüş verən bir qələvidir. Ənənəvi adı sönmüş əhəngdir.',                                                                                                                                                                                                                                                                                   descEN: 'Formula: Ca(OH)2. Molar mass: 74.093 g/mol. Density: 2.21 g/cm³. Melting point: 580°C. Calcium hydroxide is the chemical compound obtained by adding water to quicklime. It is available in crystalline white powder form. It is an alkali that gives a pasty appearance when dissolved in water. Its traditional name is slaked lime.',                                                                                     descRU: 'Формула: Ca(OH)2. Молярная масса: 74,093 г/моль. Плотность: 2,21 г/см³. Температура плавления: 580°C. Гидроксид кальция - химическое соединение, получаемое при добавлении воды к негашеной извести. Его традиционное название - гашеная известь.',                                                                         category: 'EXICIPIENT (TECHNICAL)', imageFile: 'upload-697a87d11f50cec12c2831b91626e9f9.jpg' },
  { id: 8,  titleAZ: 'Kalsium Xlorid 6-hidrat',           titleEN: 'Calcium Chloride 6-hydrate',             titleRU: 'Хлорид Кальция 6-гидрат',                   descAZ: 'Formula: CaCl2H12O6 Molar kütlə: 219.07 g/mol Sıxlıq: 1.71 g/sm³ Ərimə nöqtəsi: 30°C. Kalsium xlorid heksahidrat, aşağı temperaturlu istiliyin fazalı dəyişmə istiliyində istifadə edilə bilən zəhərli olmayan bir duz hidratdır.',                                                                                                                                                                                                                                                                                          descEN: 'Formula: CaCl2H12O6. Molar mass: 219.07 g/mol. Density: 1.71 g/cm³. Melting point: 30°C. Calcium chloride hexahydrate is a non-toxic salt hydrate used in phase change heat storage. It is widely used in solar energy storage and building applications.',                                                                                                                                                               descRU: 'Формула: CaCl2H12O6. Молярная масса: 219,07 г/моль. Гексагидрат хлорида кальция — нетоксичный солевой гидрат для аккумулирования тепла с фазовым переходом.',                                                                                                                                                               category: 'EXICIPIENT (TECHNICAL)', imageFile: 'upload-fbec9be40f1221a5d2152622faea19bc.jpg' },
  { id: 10, titleAZ: 'Kalsium Sulfat Hemihidrat',         titleEN: 'Calcium Sulfate Hemihydrate',            titleRU: 'Полугидрат Сульфата Кальция',                descAZ: 'Formula: Ca2H2O9S2 Molar kütlə: 145.15 g/mol. Kalsium sulfat hemihidratının nəmləndirilməsi gips kristalizasiyasına səbəb olur. İki hemihidratın xüsusiyyətləri, nəmləndirmə xüsusiyyətləri və gips kristallarının böyüməsi müzakirə olunur.',                                                                                                                                                                                                                                                                                 descEN: 'Formula: Ca2H2O9S2. Molar mass: 145.15 g/mol. The hydration of calcium sulphate hemihydrate leads to crystallization of gypsum. Properties of the two hemihydrates, their hydration characteristics and the crystal growth of gypsum are discussed.',                                                                                                                                                                    descRU: 'Формула: Ca2H2O9S2. Молярная масса: 145,15 г/моль. Гидратация полугидрата сульфата кальция приводит к кристаллизации гипса.',                                                                                                                                                                                                category: 'EXICIPIENT (TECHNICAL)', imageFile: 'upload-65a8b4510fb27034b94d2655532343eab.jpg' },
  { id: 11, titleAZ: 'Kalsium Karbonat',                  titleEN: 'Calcium Carbonate',                      titleRU: 'Карбонат Кальция',                          descAZ: 'Kalsium karbonat, CaCO3 düsturu olan kimyəvi birləşmədir. Qayalarda kalsit və araqonit şəklində olan ümumi bir maddədir. Yumurta qabıqlarının, ilbiz qabıqlarının, dəniz qabıqlarının və incilərin əsas komponentidir. Tibbdə mədə antasidləri üçün ucuz pəhriz kalsium əlavəsi kimi geniş istifadə olunur.',                                                                                                                                                                                                                                                                                                               descEN: 'Calcium carbonate is a chemical compound with the formula CaCO3. It is found in rocks as calcite and aragonite. It is the main component of eggshells, snail shells, seashells and pearls. Widely used medicinally as an inexpensive dietary calcium supplement for gastric antacid.',                                                                                                                                     descRU: 'Карбонат кальция — химическое соединение с формулой CaCO3. Обнаружено в горных породах в виде кальцита и арагонита. Является основным компонентом яичной скорлупы, раковин улиток и жемчуга.',                                                                                                                               category: 'EXICIPIENT (TECHNICAL)', imageFile: 'upload-87815f6f2f53e7fca9c63710329dca05d.jpg' },
  { id: 23, titleAZ: 'Kalium Alüminium Sulfat 12-hidrat', titleEN: 'Potassium Aluminium Sulfate 12-hydrate', titleRU: 'Сульфат Калия-Алюминия 12-гидрат',           descAZ: 'Formula: KAl(SO₄)₂·12H₂O Molar kütlə: 474.37 g/mol. Alüminium kalium sulfat dodekahidrat (alum), çapdan elektroliz örtüyə qədər bir çox tətbiqlərdə istifadə edilən təbii bir mineraldır.',                                                                                                                                                                                                                                                                                                                                descEN: 'Formula: KAl(SO₄)₂·12H₂O. Molar mass: 474.37 g/mol. Aluminum potassium sulfate dodecahydrate (alum) is a naturally occurring mineral used in applications from printing to electrolytic copper plating.',                                                                                                                                                                                                                  descRU: 'Формула: KAl(SO₄)₂·12H₂O. Молярная масса: 474,37 г/моль. Додекагидрат сульфата калия алюминия (квасцы) — природный минерал.',                                                                                                                                                                                               category: 'EXICIPIENT (TECHNICAL)', imageFile: 'upload-4c6ff9a723afe728472ed9798f394413.jpg' },
  { id: 15, titleAZ: 'Maqnezium Karbonat',                titleEN: 'Magnesium Carbonate',                    titleRU: 'Карбонат Магния',                           descAZ: 'Formula: MgCO3 Molar kütlə: 84.3139 g/mol Ərimə nöqtəsi: 350°C. Maqnezium karbonat ağ bərk olan qeyri-üzvi bir duzdur. Əsas istifadəsi kalsinləşdirilərək maqnezium oksidinin istehsal edilməsidir.',                                                                                                                                                                                                                                                                                                                         descEN: 'Formula: MgCO3. Molar mass: 84.3139 g/mol. Magnesium carbonate is an inorganic white solid salt. The primary use is the production of magnesium oxide by calcining. Also used in flooring, fireproofing, fire extinguishing compositions, cosmetics, and toothpaste.',                                                                                                                                                    descRU: 'Формула: MgCO3. Молярная масса: 84,3139 г/моль. Карбонат магния — неорганическая соль, белое твёрдое вещество. Основное применение — производство оксида магния путём прокаливания.',                                                                                                                                        category: 'EXICIPIENT (TECHNICAL)', imageFile: 'upload-381eb2f91347be2a0b90fa1036e710631a.jpg' },
  { id: 17, titleAZ: 'Sink Sulfat',                       titleEN: 'Zinc Sulfate',                           titleRU: 'Сульфат Цинка',                             descAZ: 'Formula: ZnSO₄ Molar kütlə: 161.47 g/mol. Sink sulfat qeyri-üzvi birləşmədir. Sink çatışmazlığını müalicə etmək üçün pəhriz əlavəsi olaraq istifadə olunur. Viskoz istehsalında laxtalanma maddəsidir.',                                                                                                                                                                                                                                                                                                                        descEN: 'Formula: ZnSO₄. Molar mass: 161.47 g/mol. Zinc sulfate is an inorganic compound used as a dietary supplement to treat zinc deficiency. The main application is as a coagulant in rayon production.',                                                                                                                                                                                                                       descRU: 'Формула: ZnSO₄. Молярная масса: 161,47 г/моль. Сульфат цинка — неорганическое соединение. Используется как пищевая добавка для лечения дефицита цинка.',                                                                                                                                                                     category: 'EXICIPIENT (TECHNICAL)', imageFile: 'upload-b98a6f32505a1a39a104488e17969b9fc.jpg' },
  { id: 21, titleAZ: 'Potasyum Hidroksid',                titleEN: 'Potassium Hydroxide',                    titleRU: 'Гидроксид Калия',                           descAZ: 'Kimyəvi formula: KOH Molekulyar çəki: 56.11 g/mol. Potasyum hidroksid qələvi əsasdır. Suda həll edildikdə istilik yayır. Kosmetika, batareyalar, gübrə istehsalı, pH tənzimlənməsi, pestisidlər, kağız və tibb sektorlarında istifadə olunur.',                                                                                                                                                                                                                                                                                   descEN: 'Chemical formula: KOH. Molecular weight: 56.11 g/mol. Potassium hydroxide is an alkaline base. It releases heat when dissolved in water. Used in cosmetics, batteries, fertilizers, pH adjustment, pesticides, paper, and medicine.',                                                                                                                                                                                    descRU: 'Химическая формула: KOH. Молекулярный вес: 56,11 г/моль. Гидроксид калия — щелочное основание. При растворении в воде выделяет тепло.',                                                                                                                                                                                     category: 'EXICIPIENT (TECHNICAL)', imageFile: 'upload-b6bfa5a77c23436bfef9b5f19dc85af8.jpg' },
  { id: 20, titleAZ: 'Potasyum Xlorid',                   titleEN: 'Potassium Chloride',                     titleRU: 'Хлорид Калия',                              descAZ: 'Formula: KCl Molar kütlə: 74.5513 g/mol Ərimə nöqtəsi: 770°C. Kalium xlorid kalium və xlordan ibarət metal halid duzudur. Qoxusuzdur, ağ kristal görünüşə malikdir.',                                                                                                                                                                                                                                                                                                                                                          descEN: 'Formula: KCl. Molar mass: 74.5513 g/mol. Potassium chloride is a metal halide salt composed of potassium and chlorine. It is odorless with a white vitreous crystal appearance.',                                                                                                                                                                                                                                        descRU: 'Формула: KCl. Молярная масса: 74,5513 г/моль. Хлорид калия — соль галогенида металла, состоящая из калия и хлора.',                                                                                                                                                                                                           category: 'EXICIPIENT (TECHNICAL)', imageFile: 'upload-662108982d84116a7cfb941030722a058a.jpg' },
  { id: 19, titleAZ: 'Ammonium Sulfat',                   titleEN: 'Ammonium Sulfate',                       titleRU: 'Сульфат Аммония',                           descAZ: 'Formula: (NH4)2SO4 Molar kütlə: 132.14 g/mol. Ammonium sulfat müxtəlif kommersiya tətbiqləri olan qeyri-üzvi duzdur. Əsasən torpaq gübrəsi kimi istifadə olunur. 21% azot və 24% kükürd ehtiva edir.',                                                                                                                                                                                                                                                                                                                       descEN: 'Formula: (NH4)2SO4. Molar mass: 132.14 g/mol. Ammonium sulphate is an inorganic salt with many commercial uses. The most common use is as a soil fertilizer. Contains 21% nitrogen and 24% sulfur.',                                                                                                                                                                                                                      descRU: 'Формула: (NH4)2SO4. Молярная масса: 132,14 г/моль. Сульфат аммония — неорганическая соль. Чаще всего используется как удобрение почвы. Содержит 21% азота и 24% серы.',                                                                                                                                                      category: 'EXICIPIENT (TECHNICAL)', imageFile: 'upload-e1052fd3474129ddd4de94d1077e47d95e.jpg' },
  { id: 24, titleAZ: 'Maqnezium Sulfat Heptahidrat',      titleEN: 'Magnesium Sulfate Heptahydrate',         titleRU: 'Гептагидрат Сульфата Магния',               descAZ: 'Formula: H14MgO11S Molar kütlə: 246.47 g/mol. Maqnezium Sülfat Heptahidrat sulfatlarla uyğun istifadə üçün orta dərəcədə suda həll olunan maqnezium mənbəyidir.',                                                                                                                                                                                                                                                                                                                                                        descEN: 'Formula: H14MgO11S. Molar mass: 246.47 g/mol. Magnesium Sulfate Heptahydrate is a moderately water soluble Magnesium source for uses compatible with sulfates.',                                                                                                                                                                                                                                                          descRU: 'Формула: H14MgO11S. Молярная масса: 246,47 г/моль. Гептагидрат сульфата магния — умеренно растворимый в воде источник магния.',                                                                                                                                                                                               category: 'EXICIPIENT (TECHNICAL)', imageFile: 'upload-77fbb19cabe43380ba1058e94593f10fa0.jpg' },
  { id: 26, titleAZ: 'Natrium Karbonat',                  titleEN: 'Sodium Carbonate',                       titleRU: 'Карбонат Натрия',                           descAZ: 'Formula: Na2CO3 Molar kütlə: 105.9888 g/mol Ərimə nöqtəsi: 851°C. Sodyum karbonat yuyucu vasitələrdə, əhəng inhibitorlarında, çamaşır ağartmaqda istifadə olunur.',                                                                                                                                                                                                                                                                                                                                                      descEN: 'Formula: Na2CO3. Molar mass: 105.9888 g/mol. Sodium carbonate is used in detergents, lime inhibitors, and laundry whiteners.',                                                                                                                                                                                                                                                                                            descRU: 'Формула: Na2CO3. Молярная масса: 105,9888 г/моль. Карбонат натрия используется в моющих средствах, ингибиторах извести.',                                                                                                                                                                                                     category: 'EXICIPIENT (TECHNICAL)', imageFile: 'upload-621d50a64d1eb8f581795fbde8f59423.jpg' },
  { id: 25, titleAZ: 'Potasyum Bromid',                   titleEN: 'Potassium Bromide',                      titleRU: 'Бромид Калия',                              descAZ: 'Formula: KBr Molar kütlə: 119.002 g/mol Ərimə nöqtəsi: 734°C Sıxlıq: 2.75 g/sm³. Kalium bromid rəngsiz, qoxusuz kristallar şəklindədir.',                                                                                                                                                                                                                                                                                                                                                                              descEN: 'Formula: KBr. Molar mass: 119.002 g/mol. Potassium bromide appears as odorless colorless crystals with a pungent bitter saline taste.',                                                                                                                                                                                                                                                                                   descRU: 'Формула: KBr. Молярная масса: 119,002 г/моль. Бромид калия — бесцветные кристаллы без запаха с горьким солёным вкусом.',                                                                                                                                                                                                      category: 'EXICIPIENT (TECHNICAL)', imageFile: 'upload-5839fa4effd12085a173a67955c7acfa.jpg' },
  { id: 32, titleAZ: 'Natrium Hidroksid',                 titleEN: 'Sodium Hydroxide',                       titleRU: 'Гидроксид Натрия',                          descAZ: 'Formula: NaOH Molar kütlə: 39.9971 g/mol. Sodyum hidroksid (kostik soda) müxtəlif istehsal proseslərində istifadə edilən çox yönlü maddədir. Sabunlarda, yuyucu vasitələrdə, drenaj təmizləyicisi kimi istifadə olunur.',                                                                                                                                                                                                                                                                                                       descEN: 'Formula: NaOH. Molar mass: 39.9971 g/mol. Sodium hydroxide (caustic soda) is a versatile substance used in manufacturing. Used in soaps, detergents, drain cleaner, paper making, and water treatment.',                                                                                                                                                                                                                  descRU: 'Формула: NaOH. Молярная масса: 39,9971 г/моль. Гидроксид натрия (каустическая сода) — универсальное вещество, используемое в различных производственных процессах.',                                                                                                                                                         category: 'EXICIPIENT (TECHNICAL)', imageFile: 'upload-e8e3d8deea667ae484319df833667fa1.jpg' },
  { id: 29, titleAZ: 'Natrium Asetat',                    titleEN: 'Sodium Acetate',                         titleRU: 'Ацетат Натрия',                             descAZ: 'Formula: CH3COONa Molar kütlə: 82.034 g/mol. Sodyum Asetat qızdırıldıqda natrium oksidə parçalanan, orta dərəcədə suda həll olunan kristal natrium mənbəyidir.',                                                                                                                                                                                                                                                                                                                                                        descEN: 'Formula: CH3COONa. Molar mass: 82.034 g/mol. Sodium Acetate is a moderately water soluble crystalline Sodium source. Acetates are excellent precursors for ultra high purity compounds and catalysts.',                                                                                                                                                                                                                   descRU: 'Формула: CH3COONa. Молярная масса: 82,034 г/моль. Ацетат натрия — умеренно растворимый в воде кристаллический источник натрия.',                                                                                                                                                                                              category: 'EXICIPIENT (TECHNICAL)', imageFile: 'upload-52336e1d73e3b8b771f36be986780a37.jpg' },
  { id: 30, titleAZ: 'Natrium Sulfat',                    titleEN: 'Sodium Sulfate',                         titleRU: 'Сульфат Натрия',                            descAZ: 'Formula: Na2SO4 Molar kütlə: 142.04 g/mol Ərimə nöqtəsi: 884°C. Sodyum sulfat kükürd turşusunun natrium duzudur.',                                                                                                                                                                                                                                                                                                                                                                                                       descEN: 'Formula: Na2SO4. Molar mass: 142.04 g/mol. Sodium sulfate is the sodium salt of sulfuric acid, occurring as a white crystalline solid.',                                                                                                                                                                                                                                                                                  descRU: 'Формула: Na2SO4. Молярная масса: 142,04 г/моль. Сульфат натрия — натриевая соль серной кислоты.',                                                                                                                                                                                                                             category: 'EXICIPIENT (TECHNICAL)', imageFile: 'upload-34615c8b509e797f876979652e9d7e04.jpg' },
  { id: 31, titleAZ: 'Natrium Xlor',                      titleEN: 'Sodium Chloride',                        titleRU: 'Хлорид Натрия',                             descAZ: 'Formula: NaCl Molar kütlə: 58.443 g/mol. Sodyum xlorid duzun kimyəvi adıdır. Sodyum bədəninizdəki su miqdarını tənzimləyən elektrolitdir.',                                                                                                                                                                                                                                                                                                                                                                          descEN: 'Formula: NaCl. Molar mass: 58.443 g/mol. Sodium chloride is the chemical name for salt. Sodium is an electrolyte that regulates the amount of water in your body.',                                                                                                                                                                                                                                                       descRU: 'Формула: NaCl. Молярная масса: 58,443 г/моль. Хлорид натрия — химическое название соли.',                                                                                                                                                                                                                                     category: 'EXICIPIENT (TECHNICAL)', imageFile: 'upload-108cde9d661858ba2d8109f106112668107b.jpg' },
  { id: 7,  titleAZ: 'Kalsium Xlorid 2-hidrat',           titleEN: 'Calcium Chloride 2-hydrate',             titleRU: 'Хлорида Кальция 2-гидрат',                  descAZ: 'Formula: CaCl2·2H2O Molar kütlə: 147.01 g/mol Sıxlıq: 1.85 g/sm3. Kalsium Xlorid Dihidrat xloridlərlə uyğun istifadə üçün mükəmməl suda həll olunan kristal Kalsium mənbəyidir.',                                                                                                                                                                                                                                                                                                                                          descEN: 'Formula: CaCl2·2H2O. Molar mass: 147.01 g/mol. Calcium Chloride Dihydrate is an excellent water soluble crystalline Calcium source for uses compatible with chlorides.',                                                                                                                                                                                                                                                  descRU: 'Формула: CaCl2·2H2O. Молярная масса: 147,01 г/моль. Дигидрат хлорида кальция — отличный водорастворимый кристаллический источник кальция.',                                                                                                                                                                                  category: 'EXICIPIENT (TECHNICAL)', imageFile: 'upload-16524b51035698d7ec2355a53483524f.jpg' },
  { id: 12, titleAZ: 'Kalsium Sulfat 2-hidrat',           titleEN: 'Calcium Sulphate 2-hydrate',             titleRU: 'Сульфата Кальция 2-гидрат',                 descAZ: 'Formula: CaSO4·2H2O Molar kütlə: 172.172 g/mol. Kalsium sulfatın əsas istifadəsi gips istehsal etməkdir. Kalsium sulfat hidratlar tofu kimi məhsullarda laxtalanma maddəsi olaraq istifadə olunur.',                                                                                                                                                                                                                                                                                                                      descEN: 'Formula: CaSO4·2H2O. Molar mass: 172.172 g/mol. The main use of calcium sulfate is to produce plaster of Paris. Calcium sulfate hydrates are used as a coagulant in products such as tofu.',                                                                                                                                                                                                                             descRU: 'Формула: CaSO4·2H2O. Молярная масса: 172,172 г/моль. Основное применение сульфата кальция — производство гипса.',                                                                                                                                                                                                            category: 'EXICIPIENT (TECHNICAL)', imageFile: 'upload-78a421605a4681007e1329a7c46afbb4f.jpg' },
  { id: 34, titleAZ: 'Kalium Polisulfid',                 titleEN: 'Potassium Polysulfide',                  titleRU: 'Полисульфид Калия',                         descAZ: 'Formula: H2KS+ Molar kütlə: 73.18 g/mol. Potasyum polisülfid qırmızı-qəhvəyi rəngli parçalar şəklindədir. Minimum K2S tərkibi 44%-dir. Səth müalicəsində, kimyada və funqisid kimi istifadə olunur.',                                                                                                                                                                                                                                                                                                                      descEN: 'Formula: H2KS+. Molar mass: 73.18 g/mol. Potassium polysulfide comes as reddish-brown lumps with a hydrogen sulfide odor. Minimum K2S content 44%. Used in surface treatment, chemistry and as a fungicide.',                                                                                                                                                                                                            descRU: 'Формула: H2KS+. Молярная масса: 73,18 г/моль. Полисульфид калия — комки красновато-коричневого цвета. Используется для обработки поверхностей и как фунгицид.',                                                                                                                                                               category: 'EXICIPIENT (TECHNICAL)', imageFile: 'upload-ae18f46395de24619d384e18b1106e086.jpg' },
  { id: 33, titleAZ: 'Natrium Hidrogen Karbonat',         titleEN: 'Sodium Hydrogen Carbonate',              titleRU: 'Гидрокарбонат Натрия',                      descAZ: 'Formula: NaHCO3 Molar kütlə: 84.0066 g/mol. Sodyum bikarbonat (çörək soda) NaHCO3 formuluna malik kimyəvi birləşmədir. Çörək bişirmədə mayalanma maddəsi kimi istifadə olunur.',                                                                                                                                                                                                                                                                                                                                         descEN: 'Formula: NaHCO3. Molar mass: 84.0066 g/mol. Sodium bicarbonate (baking soda) is used in baking as a leavening agent. Can be used as an antacid to treat acid indigestion.',                                                                                                                                                                                                                                              descRU: 'Формула: NaHCO3. Молярная масса: 84,0066 г/моль. Бикарбонат натрия (пищевая сода) используется в выпечке как разрыхлитель и как антацид.',                                                                                                                                                                                    category: 'EXICIPIENT (TECHNICAL)', imageFile: 'upload-106276e110d4fda3440acc59f1475502d3.jpg' },
  { id: 13, titleAZ: 'Dəmir Sulfat quru',                 titleEN: 'Ferrous Sulphate dried',                 titleRU: 'Сульфат Железа сушеный',                    descAZ: 'Formula: FeSO4 Molar kütlə: 151.908 g/mol. Dəmir(II) sulfat FeSO4·xH2O formulu olan duzlara aiddir. Ən çox heptahidrat (x=7) kimi mövcuddur. Dəmir çatışmazlığını müalicə etmək üçün istifadə olunur.',                                                                                                                                                                                                                                                                                                                     descEN: 'Formula: FeSO4. Molar mass: 151.908 g/mol. Iron(II) sulfate denotes a range of salts with formula FeSO4·xH2O. Most commonly exists as heptahydrate. Used medically to treat iron deficiency.',                                                                                                                                                                                                                           descRU: 'Формула: FeSO4. Молярная масса: 151,908 г/моль. Сульфат железа(II) — ряд солей с формулой FeSO4·xH2O. Используется для лечения дефицита железа.',                                                                                                                                                                           category: 'EXICIPIENT (TECHNICAL)', imageFile: 'upload-8fe3b7ee8730a55248f4b157ff106935f.jpg' },
  { id: 14, titleAZ: 'Dəmir Sulfat 7-hidrat',             titleEN: 'Ferrous Sulphate 7-hydrate',             titleRU: 'Сульфат Железа 7-гидрат',                   descAZ: 'Formula: FeSO4·xH2O Molar kütlə: 278.02 g/mol Sıxlıq: 1895 g/sm3 Ərimə nöqtəsi: 60-64°C. Dəmir(II) Sülfat Heptahidrat sulfatlarla uyğun istifadə üçün suda həll olunan Dəmir mənbəyidir.',                                                                                                                                                                                                                                                                                                                                 descEN: 'Formula: FeSO4·xH2O. Molar mass: 278.02 g/mol. Iron(II) Sulfate Heptahydrate is a moderately water and acid soluble Iron source for uses compatible with sulfates.',                                                                                                                                                                                                                                                      descRU: 'Формула: FeSO4·xH2O. Молярная масса: 278,02 г/моль. Гептагидрат сульфата железа(II) — умеренно растворимый источник железа.',                                                                                                                                                                                                category: 'EXICIPIENT (TECHNICAL)', imageFile: 'upload-16b3748671f9ea78bf0ec83b92932255.jpg' },
  { id: 16, titleAZ: 'Maqnezium Xlorid 6-hidrat',         titleEN: 'Magnesium Chloride 6-hydrate',           titleRU: 'Хлорид Магния 6-гидрат',                    descAZ: 'Formula: Cl2H12MgO6 Molar kütlə: 203.31 g/mol. Maqnezium xlorid heksahidrat kimya və molekulyar biologiya tətbiqlərində maqnezium ionu mənbəyi kimi geniş istifadə olunur.',                                                                                                                                                                                                                                                                                                                                               descEN: 'Formula: Cl2H12MgO6. Molar mass: 203.31 g/mol. Magnesium Chloride Hexahydrate is widely used as a source of magnesium ion in chemistry and molecular biology applications.',                                                                                                                                                                                                                                              descRU: 'Формула: Cl2H12MgO6. Молярная масса: 203,31 г/моль. Гексагидрат хлорида магния широко используется как источник иона магния в химии и молекулярной биологии.',                                                                                                                                                                category: 'EXICIPIENT (TECHNICAL)', imageFile: 'upload-9d141c0c042ddf3eaf3788e36c266152.jpg' },
  { id: 28, titleAZ: 'Kalium Hidrogen Karbonat',          titleEN: 'Potassium Hydrogen Carbonate',           titleRU: 'Карбонат Водорода Калия',                   descAZ: 'Formula: KHCO3 Molar kütlə: 100.115 g/mol. Qida məhsullarına əlavə olaraq, məsələn, qazlı içkilərdə və mayalanma agenti kimi istifadə edilə bilər.',                                                                                                                                                                                                                                                                                                                                                                 descEN: 'Formula: KHCO3. Molar mass: 100.115 g/mol. Potassium hydrogen carbonate can be used as a food additive in effervescent drinks and as a leavening agent.',                                                                                                                                                                                                                                                                 descRU: 'Формула: KHCO3. Молярная масса: 100,115 г/моль. Гидрокарбонат калия используется как пищевая добавка в шипучих напитках и как разрыхлитель.',                                                                                                                                                                                 category: 'EXICIPIENT (TECHNICAL)', imageFile: 'upload-b1a6a6dc8c5092cbcfb487f1ebb42a0c.jpg' },
  { id: 35, titleAZ: 'Kalium Karbonat',                   titleEN: 'Potassium Carbonate',                    titleRU: 'Карбонат Калия',                            descAZ: 'Formula: K2CO3 Molar kütlə: 138.205 g/mol. Kalium karbonat K2CO3 formulu olan qeyri-üzvi birləşmədir. Suda həll olan ağ duzdur. Sabun, şüşə istehsalında, yanğınsöndürmə vasitələrində istifadə olunur.',                                                                                                                                                                                                                                                                                                                  descEN: 'Formula: K2CO3. Molar mass: 138.205 g/mol. Potassium carbonate is a white salt soluble in water. Mainly used in the production of soap and glass, also in fire extinguishers.',                                                                                                                                                                                                                                           descRU: 'Формула: K2CO3. Молярная масса: 138,205 г/моль. Карбонат калия — белая соль, растворимая в воде. Используется в производстве мыла и стекла.',                                                                                                                                                                                 category: 'EXICIPIENT (TECHNICAL)', imageFile: 'upload-6c9521b185236e95536dca3997b63493.jpg' },
  { id: 27, titleAZ: 'Maqnezium Sulfat quru',             titleEN: 'Magnesium Sulfate dried',                titleRU: 'Сульфат Магния сушеный',                    descAZ: 'Formula: MgSO4 Molar kütlə: 120.366 g/mol. Maqnezium sulfat heptahidrat, monohidrat, susuz və ya qurudulmuş formada satılır. Təbii olaraq dəniz suyunda, mineral bulaqlarda olur.',                                                                                                                                                                                                                                                                                                                                   descEN: 'Formula: MgSO4. Molar mass: 120.366 g/mol. Magnesium sulfate is available as heptahydrate, monohydrate, anhydrous or dried form. Occurs naturally in seawater and mineral springs.',                                                                                                                                                                                                                                      descRU: 'Формула: MgSO4. Молярная масса: 120,366 г/моль. Сульфат магния доступен в форме гептагидрата, моногидрата, безводной или сухой формы.',                                                                                                                                                                                       category: 'EXICIPIENT (TECHNICAL)', imageFile: 'upload-4b70cde502bab9f17fcaa465b10dd451c.jpg' },
  { id: 22, titleAZ: 'Kalium Sulfat',                     titleEN: 'Potassium Sulfate',                      titleRU: 'Сульфат Калия',                             descAZ: 'Formula: K2SO4 Molar kütlə: 174.259 g/mol Ərimə nöqtəsi: 1069°C. Kalium Sülfat sulfatlarla uyğun istifadə üçün suda həll olunan kalium mənbəyidir.',                                                                                                                                                                                                                                                                                                                                                                    descEN: 'Formula: K2SO4. Molar mass: 174.259 g/mol. Potassium Sulfate is a moderately water soluble Potassium source for uses compatible with sulfates.',                                                                                                                                                                                                                                                                          descRU: 'Формула: K2SO4. Молярная масса: 174,259 г/моль. Сульфат калия — умеренно растворимый в воде источник калия.',                                                                                                                                                                                                                 category: 'EXICIPIENT (TECHNICAL)', imageFile: 'upload-e38a65013863b657656d1c1cd5ad9f7a.jpg' },
  { id: 18, titleAZ: 'Karbamid',                          titleEN: 'Urea',                                   titleRU: 'Карбамид',                                  descAZ: 'Formula: CH4N2O Molar kütlə: 60.06 g/mol Ərimə nöqtəsi: 133°C. Karbamid üzvi birləşmədir. Onun formulu H₂N-CO-NH₂-dur. İlk dəfə 1773-cü ildə kəşf edilmişdir.',                                                                                                                                                                                                                                                                                                                                                         descEN: 'Formula: CH4N2O. Molar mass: 60.06 g/mol. Urea is an organic compound with formula H₂N-CO-NH₂. First discovered in 1773, precisely synthesized by Wöhler in 1828.',                                                                                                                                                                                                                                                      descRU: 'Формула: CH4N2O. Молярная масса: 60,06 г/моль. Карбамид — органическое соединение с формулой H₂N-CO-NH₂.',                                                                                                                                                                                                                   category: 'EXICIPIENT (TECHNICAL)', imageFile: 'upload-ff7c3a7f645eacaa06104b4a3c9425c43.jpg' },
  { id: 3,  titleAZ: 'Ammonium Xlorid',                   titleEN: 'Ammonium Chloride',                      titleRU: 'Хлорид Aммония',                            descAZ: 'Formula: NH4Cl Molar kütlə: 53.491 g/mol. Ammonium xlorid NH₄Cl formuluna malik kimyəvi birləşmədir. Ağ kristalları olan, suda həll olunan duzdur. Bəzi vulkanik dəliklərin ətrafında mineral şəklindədir.',                                                                                                                                                                                                                                                                                                                descEN: 'Formula: NH4Cl. Molar mass: 53.491 g/mol. Ammonium chloride is a chemical compound with formula NH₄Cl. A salt with white crystals, highly soluble in water.',                                                                                                                                                                                                                                                            descRU: 'Формула: NH4Cl. Молярная масса: 53,491 г/моль. Хлорид аммония — химическое соединение с формулой NH₄Cl. Соль с белыми кристаллами.',                                                                                                                                                                                         category: 'EXICIPIENT (TECHNICAL)', imageFile: 'upload-64c110349fbb8fc53c7791040aef8d3bfb.jpg' },
  { id: 39, titleAZ: 'ShinePro',                          titleEN: 'ShinePro',                               titleRU: 'ShinePro',                                  descAZ: '',                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                               descEN: '',                                                                                                                                                                                                                                                                                                                                                                                                                         descRU: 'ShinePro — однокомпонентное сильнощелочное средство нового поколения для мойки автомобилей, грузовиков, танкеров, двигателей и т.д. Разбавить в воде в соотношении 1:30-80. Показатель pH: 8. Срок хранения: 3 года.',                                                                                                        category: 'OTHER CHEMICALS',        imageFile: 'upload-b83474d835e07f4df88ce43d59d9408c.png' },
  { id: 40, titleAZ: 'Moyka Şampunu',                     titleEN: 'Moyka Şampunu',                          titleRU: 'Moyka Şampunu',                             descAZ: '',                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                               descEN: '',                                                                                                                                                                                                                                                                                                                                                                                                                         descRU: '',                                                                                                                                                                                                                                                                                                                             category: 'OTHER CHEMICALS',        imageFile: 'upload-5ab15973b5222cd83c931201abeb519a.jpeg' },
]

// ─── About text (from DB) ─────────────────────────────────────────────────
const ABOUT = {
  az: `Kimyəvi xammal tədarükü və marketinq şirkəti olan firmamız Alphachem 2000-ci ildən xidmətə başlamışdır. Şirkətimiz Azərbaycanın kimya sənayesinin müxtəlif sahələrində illərin təcrübəsi və biliyi olan həmkarlarımız və güclü infrastrukturu ilə sektorumuza ən qısa zamanda, ən etibarlı mənbələrdən, ən yaxşı xidməti təqdim etməyi qarşısına məqsəd qoyub.\n\nBaşda Əczaçılıq, Qida, Kosmetika və Baytarlıq olmaqla Azərbaycan iqtisadiyyatının digər sektorları üçün lazım olan kimyəvi xammalın tədarükü şirkətimizin əsas diqqət mərkəzindədir. Məhsullarımız keyfiyyət siyasətimizə uyğun olaraq Səhiyyə Nazirliyinin müəyyən etdiyi şərtlərə cavab verən saxlama şəraitinə uyğun anbarlarda saxlanılır. Alphachem ölkə daxilində və xaricdə sektorun aparıcı, nüfuzlu təşkilatları ilə əməkdaşlıq edir.\n\nKomandamızı fərqləndirən üstünlüklər: müştərilərimizin daxili və xaricdəki xammal ehtiyaclarını lazımi mənbələrdən ən qısa müddətdə və ən sərfəli qiymətlərlə təmin etmək; məhsulların düzgün və keyfiyyətli sənədlərlə işini təmin etmək; müştərilərimizin nüfuzlu və seçilmiş təchizatçıları arasında olmaq üçün ilk növbədə onların məmnuniyyətinin vacibliyini dərk etmək.\n\nPrinsiplərimizə sadiq olaraq, sizi yüksək standartlara uyğun məhsullarla təmin etməyi qarşımıza məqsəd qoyuruq. Çünki müştərilərin bizdən razı qalması, təkmilləşməyimiz və irəli getməyimizin əsas motivasiyasıdır!`,
  en: `Our company Alphachem has been in the business of supplying and distributing chemical raw materials since 2000. With our colleagues with many years of experience and knowledge in various areas of the chemical industry in Azerbaijan and a strong infrastructure, the company strives to provide the best service for our sector as soon as possible, from the most reliable sources.\n\nThe main activity of the company is the supply of chemical equipment for other sectors of the Azerbaijani economy, especially pharmaceuticals, food, cosmetics and veterinary medicine. Our products are stored in warehouses that comply with the conditions established by the Ministry of Health in accordance with our quality policy.\n\nThe advantages that distinguish our team: delivery of goods to local and foreign customers from the necessary sources in the shortest possible time and at the most affordable prices; provide correct and high-quality product documentation; understand the importance of meeting the needs of your customers in order to be among the most influential and chosen suppliers.\n\nAdhering to our principles, we strive to provide you with products that meet the highest standards. Because a satisfied customer is the main motivation for us to improve and move forward!`,
  ru: `Наша компания Alphachem, занимающаяся поставкой и сбытом химического сырья, работает с 2000 года. С нашими коллегами с многолетним опытом в различных областях химической промышленности Азербайджана, компания стремится предоставить лучший сервис как можно скорее, из самых надежных источников.\n\nОсновным направлением деятельности компании является поставка химического сырья для других секторов экономики Азербайджана, особенно фармацевтики, продуктов питания, косметики и ветеринарии. Наша продукция хранится на складах, которые соответствуют условиям, установленным Министерством Здравоохранения.\n\nПреимущества, которые выделяют нашу команду: доставка товара клиентам из необходимых источников в кратчайшие сроки и по наиболее доступным ценам; обеспечивать правильную и качественную документацию продуктов; понимать важность удовлетворения потребностей своих клиентов.\n\nСледуя нашим принципам, мы стремимся предоставлять вам продукцию, соответствующую самым высоким стандартам. Потому что довольный клиент является для нас основной мотивацией совершенствоваться и двигаться вперед!`,
}

// ─── Slider images (from DB) ──────────────────────────────────────────────
const SLIDER_FILES = [
  { order: 1, file: 'upload-53a6a456ba10d3bf317104dc6cb3893801.png' },
  { order: 2, file: 'upload-a73f64b4ada6949859e777d9a8916442.png' },
  { order: 3, file: 'upload-b87e4cf420d49b1ab2d4050ca22246c4.png' },
]

async function uploadFromFile(imageFile: string, bucket: string, destName: string): Promise<string | null> {
  const localPath = join(UPLOADS_DIR, imageFile)
  if (!existsSync(localPath)) {
    console.warn(`  ✗ Not found in scripts/uploads/: ${imageFile}`)
    return null
  }
  try {
    const buffer = readFileSync(localPath)
    const ext = imageFile.split('.').pop() ?? 'jpg'
    const mimeMap: Record<string, string> = {
      png: 'image/png', jpg: 'image/jpeg', jpeg: 'image/jpeg', webp: 'image/webp', gif: 'image/gif',
    }
    const contentType = mimeMap[ext.toLowerCase()] ?? 'application/octet-stream'
    const path = `${destName}.${ext}`
    const { error } = await supabase.storage.from(bucket).upload(path, buffer, { contentType, upsert: true })
    if (error) { console.warn(`  ✗ Storage error for ${path}:`, error.message); return null }
    return supabase.storage.from(bucket).getPublicUrl(path).data.publicUrl
  } catch (e) {
    console.warn(`  ✗ Upload failed for ${imageFile}:`, (e as Error).message)
    return null
  }
}

function makeSlug(name: string, used: Set<string>): string {
  let base = slugify(name.trim(), { lower: true, strict: true })
  if (!base) base = `product-${Math.random().toString(36).slice(2, 8)}`
  let slug = base, i = 1
  while (used.has(slug)) slug = `${base}-${i++}`
  used.add(slug)
  return slug
}

async function seed() {
  console.log('🌱 Alphachem seed starting...\n')

  // 1. Categories
  console.log('📂 Seeding categories...')
  const { data: cats, error: catErr } = await supabase
    .from('categories')
    .upsert(CATEGORIES, { onConflict: 'slug' })
    .select()
  if (catErr) { console.error('Category error:', catErr); process.exit(1) }
  const catMap = new Map(cats!.map((c: {slug: string; id: string}) => [c.slug, c.id]))
  console.log(`  ✓ ${cats!.length} categories\n`)

  // 2. Slider
  console.log('🖼️  Seeding slider images...')
  for (const s of SLIDER_FILES) {
    const publicUrl = await uploadFromFile(s.file, 'slider', `slide-${s.order}`)
    if (publicUrl) {
      await supabase.from('slider_images').upsert({ image_url: publicUrl, sort_order: s.order, active: true })
      console.log(`  ✓ slide-${s.order}`)
    }
  }
  console.log()

  // 3. Site content
  console.log('📝 Seeding site content...')
  await supabase.from('site_content').upsert([
    { key: 'about_text', locale: 'az', value: ABOUT.az },
    { key: 'about_text', locale: 'en', value: ABOUT.en },
    { key: 'about_text', locale: 'ru', value: ABOUT.ru },
    { key: 'contact_address_az', locale: 'az', value: 'Azərbaycan, Bakı şəhəri.' },
    { key: 'contact_address_az', locale: 'en', value: 'Azerbaijan, Baku' },
    { key: 'contact_address_az', locale: 'ru', value: 'Азербайджан, г. Баку' },
  ], { onConflict: 'key,locale' })
  console.log('  ✓ Site content\n')

  // 4. Products
  console.log('🧪 Seeding products...')
  const usedSlugs = new Set<string>()

  for (const p of PRODUCTS) {
    const catSlug = mapCategory(p.category)
    const catId = catMap.get(catSlug)
    const slug = makeSlug(p.titleAZ, usedSlugs)

    // Upload product image from local scripts/uploads/
    const storedUrl = await uploadFromFile(p.imageFile, 'products', `product-${p.id}`)

    const { data: product, error: prodErr } = await supabase
      .from('products')
      .upsert({ slug, category_id: catId, image_url: storedUrl, sort_order: p.id, active: true }, { onConflict: 'slug' })
      .select()
      .single()

    if (prodErr || !product) { console.warn(`  ✗ ${p.titleAZ}:`, prodErr?.message); continue }

    await supabase.from('product_translations').upsert([
      { product_id: product.id, locale: 'az', name: p.titleAZ.trim(), description: p.descAZ || null },
      { product_id: product.id, locale: 'en', name: p.titleEN.trim(), description: p.descEN || null },
      { product_id: product.id, locale: 'ru', name: p.titleRU.trim(), description: p.descRU || null },
    ], { onConflict: 'product_id,locale' })

    console.log(`  ✓ [${p.id}] ${p.titleAZ} → ${slug}`)
  }

  console.log('\n✅ Seed complete!')
}

seed().catch(console.error)
